/// Bootstrap assembler web app served at `GET /cleona` (Architecture §19.6.6).
///
/// Self-contained HTML+JS — no external dependencies (no CDN scripts, no
/// external fetches besides same-origin binary/fragment downloads and, when
/// applicable, WebSocket connections to public Nostr relays, both explicitly
/// permitted by §19.6.6). Runs entirely in Bob's browser — Bob does not have
/// Cleona installed yet — to:
///
///  1. Read the invite link parameters (`s`/`h`/`m`/`v`/`f`) from the URL
///     hash fragment (never sent to any server, §19.6.4).
///  2. Detect Bob's platform from the User-Agent.
///  3. Verify the maintainer's Ed25519 signature over the binary hash map
///     *before* downloading anything — an invalid signature aborts the flow.
///  4. Download the complete binary from the serving node, or fall back to
///     per-platform Reed-Solomon erasure fragments (§19.6.2 parameters) and
///     reassemble them in the browser.
///  5. Verify the assembled binary's SHA-256 hash against the invite link.
///  6. Offer the verified binary for download.
///
/// The GF(256) Reed-Solomon decoder is a byte-for-byte port of
/// `lib/core/erasure/reed_solomon.dart` (same Cauchy-matrix construction,
/// same AES-polynomial field, same Gaussian elimination order) and the
/// Ed25519 verifier follows RFC 8032 (extended twisted-Edwards coordinates,
/// `a = -1`, non-cofactored verification equation `[S]B == R + [k]A`), the
/// same primitive `SodiumFFI.verifyEd25519` exposes via libsodium. Both were
/// cross-checked against vectors generated by the real Dart implementations
/// in this repository (`ReedSolomon` and `SodiumFFI`, via libsodium) before
/// being embedded here — see the embedded self-tests below, which run the
/// same vectors again at page load and fail closed (refuse to proceed) if
/// the browser's JS engine ever disagrees.
class BootstrapWebApp {
  /// The complete HTML document as a UTF-8 string, ready to be served
  /// verbatim as the body of `GET /cleona`.
  ///
  /// [maintainerPublicKeyHex] is the Ed25519 maintainer public key (same
  /// value as `UpdateChecker.maintainerPublicKeyHex`) — injected here so it
  /// is not duplicated/hardcoded in this file.
  static String html({required String maintainerPublicKeyHex}) {
    return r'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="robots" content="noindex, nofollow">
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'self' data:; connect-src 'self' wss://relay.damus.io wss://nos.lol wss://relay.snort.social wss://relay.primal.net; base-uri 'none'; form-action 'none'; frame-ancestors 'none';">
<title>Cleona — Install</title>
<style>
  :root {
    color-scheme: dark light;
    --bg: #0b0e14;
    --bg-elevated: #131824;
    --border: #232a3a;
    --text: #e8ecf4;
    --text-dim: #8a93a6;
    --accent: #4f8cff;
    --accent-dim: #1c2c4d;
    --ok: #35c46a;
    --warn: #e6a23c;
    --err: #e5484d;
    --mono: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
    --sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  }
  @media (prefers-color-scheme: light) {
    :root {
      --bg: #f5f6f8;
      --bg-elevated: #ffffff;
      --border: #dde1e8;
      --text: #1a1e27;
      --text-dim: #5b6472;
      --accent: #2f6fe0;
      --accent-dim: #dce8fc;
      --ok: #1f9d53;
      --warn: #b9770e;
      --err: #c8323a;
    }
  }
  * { box-sizing: border-box; }
  html, body {
    margin: 0; padding: 0;
    background: var(--bg);
    color: var(--text);
    font-family: var(--sans);
    min-height: 100%;
  }
  body {
    display: flex;
    justify-content: center;
    padding: 32px 16px 64px;
  }
  .card { width: 100%; max-width: 480px; }
  .brand { display: flex; align-items: center; gap: 12px; margin-bottom: 24px; }
  .brand-mark {
    width: 40px; height: 40px; border-radius: 10px; flex: none;
    background: linear-gradient(135deg, var(--accent), #7b5cff);
    display: flex; align-items: center; justify-content: center;
    font-weight: 700; color: #fff; font-size: 18px;
  }
  .brand-name { font-size: 20px; font-weight: 600; letter-spacing: -0.01em; }
  .brand-sub { font-size: 13px; color: var(--text-dim); margin-top: 2px; }
  .panel {
    background: var(--bg-elevated);
    border: 1px solid var(--border);
    border-radius: 14px;
    padding: 24px;
    margin-bottom: 16px;
  }
  .row { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 6px; font-size: 13px; }
  .row .k { color: var(--text-dim); }
  .status-line { font-size: 15px; font-weight: 500; margin: 10px 0 16px; min-height: 20px; }
  .progress-track { height: 8px; border-radius: 999px; background: var(--border); overflow: hidden; margin-bottom: 8px; }
  .progress-fill {
    height: 100%; width: 0%; border-radius: 999px;
    background: linear-gradient(90deg, var(--accent), #7b5cff);
    transition: width 0.25s ease;
  }
  .progress-label { font-size: 12px; color: var(--text-dim); text-align: right; min-height: 16px; }
  .steps { display: flex; gap: 6px; margin: 16px 0 4px; }
  .step { flex: 1; height: 4px; border-radius: 999px; background: var(--border); }
  .step.done { background: var(--ok); }
  .step.active { background: var(--accent); }
  .badge {
    display: inline-flex; align-items: center; gap: 6px;
    font-size: 12px; font-weight: 600; padding: 4px 10px; border-radius: 999px;
    background: var(--accent-dim); color: var(--accent);
  }
  .btn {
    display: block; width: 100%; text-align: center;
    padding: 12px 16px; border-radius: 10px; border: none;
    font-size: 15px; font-weight: 600; cursor: pointer;
    background: var(--accent); color: #fff;
    text-decoration: none;
  }
  .btn:disabled { opacity: 0.45; cursor: not-allowed; }
  .banner {
    display: none;
    border-radius: 10px; padding: 12px 14px; font-size: 13px; margin-bottom: 16px; line-height: 1.5;
  }
  .banner.show { display: block; }
  .banner.warn { background: rgba(230, 162, 60, 0.12); border: 1px solid rgba(230, 162, 60, 0.4); color: var(--warn); }
  .banner.err { background: rgba(229, 72, 77, 0.12); border: 1px solid rgba(229, 72, 77, 0.4); color: var(--err); }
  .banner.ok { background: rgba(53, 196, 106, 0.12); border: 1px solid rgba(53, 196, 106, 0.4); color: var(--ok); }
  .platform-picker { display: flex; flex-wrap: wrap; gap: 8px; margin: 12px 0 4px; }
  .platform-picker button {
    padding: 8px 12px; border-radius: 8px; border: 1px solid var(--border);
    background: transparent; color: var(--text-dim); font-size: 13px; cursor: pointer;
  }
  .platform-picker button.active { border-color: var(--accent); color: var(--accent); background: var(--accent-dim); }
  .log {
    font-family: var(--mono); font-size: 11px; color: var(--text-dim);
    background: var(--bg); border: 1px solid var(--border); border-radius: 10px;
    padding: 10px 12px; max-height: 140px; overflow-y: auto; white-space: pre-wrap; word-break: break-all;
  }
  .footnote { font-size: 12px; color: var(--text-dim); line-height: 1.6; margin-top: 16px; }
  .hash { font-family: var(--mono); font-size: 11px; word-break: break-all; color: var(--text-dim); }
  details { margin-top: 8px; }
  summary { cursor: pointer; font-size: 12px; color: var(--text-dim); }
</style>
</head>
<body>
<div class="card">
  <div class="brand">
    <div class="brand-mark">C</div>
    <div>
      <div class="brand-name">Cleona</div>
      <div class="brand-sub">Decentralized secure messenger — installer</div>
    </div>
  </div>

  <div class="panel">
    <span class="badge" id="platform-badge">Detecting platform…</span>
    <div class="platform-picker" id="platform-picker"></div>

    <div class="status-line" id="status-line">Reading invite link…</div>

    <div class="steps" id="steps">
      <div class="step" data-step="fetch"></div>
      <div class="step" data-step="verify"></div>
      <div class="step" data-step="ready"></div>
    </div>

    <div class="progress-track"><div class="progress-fill" id="progress-fill"></div></div>
    <div class="progress-label" id="progress-label">&nbsp;</div>

    <div class="banner warn" id="banner-warn"></div>
    <div class="banner err" id="banner-err"></div>
    <div class="banner ok" id="banner-ok"></div>

    <button class="btn" id="action-btn" disabled>Preparing…</button>

    <details>
      <summary>Details</summary>
      <div class="row"><span class="k">Version</span><span id="detail-version">—</span></div>
      <div class="row"><span class="k">Expected SHA-256</span></div>
      <div class="hash" id="detail-hash">—</div>
      <div class="log" id="log" style="margin-top:10px;"></div>
    </details>
  </div>

  <div class="footnote">
    This page runs entirely in your browser — nothing is sent anywhere
    except to Cleona nodes and public Nostr relays while looking for a copy
    of the installer. The download is verified against a cryptographic
    signature from the Cleona maintainer before it is offered to you. Your
    browser may warn about this being an "insecure" download because it is
    served over plain HTTP — Cleona nodes have no fixed domain name, so no
    HTTPS certificate is possible for them. This is expected: the file
    itself is still independently verified below by SHA-256 hash and
    Ed25519 signature, both of which travelled to you through the invite
    link — a separate channel from this download.
  </div>
</div>
<script>
(function () {
'use strict';

// Injected by BootstrapWebApp.html() — the Ed25519 maintainer public key
// (hex), same value as UpdateChecker.maintainerPublicKeyHex. Kept as a
// dedicated string constant (rather than baked into the verify call) so the
// Dart-side .replaceFirst() has a single, unambiguous line to target.
var MAINTAINER_PUBLIC_KEY_HEX = "__MAINTAINER_PUBLIC_KEY_HEX__";

// ============================================================================
// UI helpers
// ============================================================================

function $(id) { return document.getElementById(id); }

var logLines = [];
function log(msg) {
  var d = new Date();
  var ts = ('0' + d.getHours()).slice(-2) + ':' + ('0' + d.getMinutes()).slice(-2) + ':' + ('0' + d.getSeconds()).slice(-2);
  logLines.push('[' + ts + '] ' + msg);
  if (logLines.length > 300) logLines.shift();
  var el = $('log');
  if (el) {
    el.textContent = logLines.join('\n');
    el.scrollTop = el.scrollHeight;
  }
}

function setStatus(text) { $('status-line').textContent = text; }

function setProgress(fraction, label) {
  var pct = Math.max(0, Math.min(1, fraction)) * 100;
  $('progress-fill').style.width = pct.toFixed(1) + '%';
  $('progress-label').textContent = label || '';
}

function setStep(name, state) {
  var el = document.querySelector('.step[data-step="' + name + '"]');
  if (!el) return;
  el.classList.remove('done', 'active');
  if (state) el.classList.add(state);
}

function showBanner(kind, text) {
  ['warn', 'err', 'ok'].forEach(function (k) {
    var el = $('banner-' + k);
    el.classList.remove('show');
    el.textContent = '';
    if (k === kind && text) { el.textContent = text; el.classList.add('show'); }
  });
}

function setAction(label, onClick, enabled) {
  var btn = $('action-btn');
  btn.textContent = label;
  btn.disabled = !enabled;
  btn.onclick = onClick || null;
}

function formatBytes(n) {
  if (!n && n !== 0) return '';
  var units = ['B', 'KB', 'MB', 'GB'];
  var i = 0;
  var v = n;
  while (v >= 1024 && i < units.length - 1) { v /= 1024; i++; }
  return v.toFixed(v < 10 && i > 0 ? 1 : 0) + ' ' + units[i];
}

// ============================================================================
// Byte / encoding helpers
// ============================================================================

function bytesToHex(bytes) {
  var hex = '';
  for (var i = 0; i < bytes.length; i++) hex += bytes[i].toString(16).padStart(2, '0');
  return hex;
}
function hexToBytes(hex) {
  if (hex.length % 2 !== 0) throw new Error('odd-length hex string');
  var out = new Uint8Array(hex.length / 2);
  for (var i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i * 2, 2), 16);
  return out;
}
function base64ToBytes(b64) {
  var bin = atob(b64);
  var out = new Uint8Array(bin.length);
  for (var i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
function utf8ToBytes(str) { return new TextEncoder().encode(str); }
function bytesToUtf8(bytes) { return new TextDecoder('utf-8').decode(bytes); }
function concatBytes() {
  var total = 0;
  for (var i = 0; i < arguments.length; i++) total += arguments[i].length;
  var out = new Uint8Array(total);
  var off = 0;
  for (var i = 0; i < arguments.length; i++) { out.set(arguments[i], off); off += arguments[i].length; }
  return out;
}
async function sha256Hex(bytes) {
  var digest = await crypto.subtle.digest('SHA-256', bytes);
  return bytesToHex(new Uint8Array(digest));
}
async function sha512Bytes(bytes) {
  var digest = await crypto.subtle.digest('SHA-512', bytes);
  return new Uint8Array(digest);
}

// ============================================================================
// GF(256) Reed-Solomon decoder — byte-for-byte port of the Cauchy-matrix
// construction and Gaussian-elimination decode in
// lib/core/erasure/reed_solomon.dart (AES field, polynomial 0x11B / reduction
// constant 0x1B). Cross-checked at page load (rsSelfTest) against a vector
// generated by the real Dart ReedSolomon class.
// ============================================================================

var GF_MUL_TABLE = new Uint8Array(65536);
var GF_INV_TABLE = new Uint8Array(256);

function gfMulSlow(a, b) {
  a &= 0xFF; b &= 0xFF;
  var result = 0;
  for (var i = 0; i < 8; i++) {
    if (b & 1) result ^= a;
    var hi = a & 0x80;
    a = (a << 1) & 0xFF;
    if (hi) a ^= 0x1B;
    b >>= 1;
  }
  return result;
}

(function buildGfTables() {
  for (var a = 0; a < 256; a++) {
    for (var b = 0; b < 256; b++) {
      GF_MUL_TABLE[(a << 8) | b] = gfMulSlow(a, b);
    }
  }
  for (var a2 = 1; a2 < 256; a2++) {
    for (var b2 = 1; b2 < 256; b2++) {
      if (GF_MUL_TABLE[(a2 << 8) | b2] === 1) { GF_INV_TABLE[a2] = b2; break; }
    }
  }
})();

function gfMul(a, b) { return GF_MUL_TABLE[((a & 0xFF) << 8) | (b & 0xFF)]; }
function gfInv(a) { return GF_INV_TABLE[a & 0xFF]; }

// Cauchy coefficient: X[p] = p + 1, Y[i] = m + i + 1, coeff = 1 / (X[p] xor Y[i]).
function cauchyCoeff(m, p, i) {
  return gfInv(((p + 1) ^ (m + i + 1)) & 0xFF);
}

// Port of ReedSolomon.decode(). fragmentsMap: Map<fragmentIndex, Uint8Array>.
function rsDecode(fragmentsMap, originalSize, n, k) {
  var m = n - k;
  if (fragmentsMap.size < k) {
    throw new Error('Need at least ' + k + ' fragments, got ' + fragmentsMap.size);
  }

  var haveAllData = true;
  for (var i = 0; i < k; i++) {
    if (!fragmentsMap.has(i)) { haveAllData = false; break; }
  }
  if (haveAllData) {
    var fragSize0 = fragmentsMap.get(0).length;
    var result0 = new Uint8Array(fragSize0 * k);
    for (var i2 = 0; i2 < k; i2++) result0.set(fragmentsMap.get(i2), i2 * fragSize0);
    return result0.slice(0, originalSize);
  }

  var available = [];
  for (var i3 = 0; i3 < k; i3++) if (fragmentsMap.has(i3)) available.push(i3);
  for (var p = 0; p < m && available.length < k; p++) {
    if (fragmentsMap.has(k + p)) available.push(k + p);
  }
  if (available.length < k) {
    throw new Error('Need at least ' + k + ' fragments, got ' + available.length);
  }

  var fragSize = fragmentsMap.get(available[0]).length;

  var matrix = [];
  for (var r = 0; r < k; r++) {
    var rowIdx = available[r];
    var row = new Uint8Array(k);
    if (rowIdx < k) {
      row[rowIdx] = 1;
    } else {
      var pp = rowIdx - k;
      for (var c = 0; c < k; c++) row[c] = cauchyCoeff(m, pp, c);
    }
    matrix.push(row);
  }

  var w = 2 * k;
  var aug = [];
  for (var r2 = 0; r2 < k; r2++) {
    var row2 = new Uint8Array(w);
    row2.set(matrix[r2], 0);
    row2[k + r2] = 1;
    aug.push(row2);
  }

  for (var col = 0; col < k; col++) {
    var pivotRow = -1;
    for (var r3 = col; r3 < k; r3++) { if (aug[r3][col] !== 0) { pivotRow = r3; break; } }
    if (pivotRow < 0) throw new Error('Encoding matrix is singular — cannot decode');
    if (pivotRow !== col) { var tmp = aug[col]; aug[col] = aug[pivotRow]; aug[pivotRow] = tmp; }
    var pivotInv = gfInv(aug[col][col]);
    for (var c2 = 0; c2 < w; c2++) aug[col][c2] = gfMul(aug[col][c2], pivotInv);
    for (var r4 = 0; r4 < k; r4++) {
      if (r4 === col) continue;
      var factor = aug[r4][col];
      if (factor === 0) continue;
      for (var c3 = 0; c3 < w; c3++) aug[r4][c3] ^= gfMul(factor, aug[col][c3]);
    }
  }

  var inv = [];
  for (var r5 = 0; r5 < k; r5++) {
    var row3 = new Uint8Array(k);
    for (var c4 = 0; c4 < k; c4++) row3[c4] = aug[r5][k + c4];
    inv.push(row3);
  }

  var availArrs = available.map(function (idx) { return fragmentsMap.get(idx); });
  var result = new Uint8Array(fragSize * k);
  var fb = new Uint8Array(k);
  for (var j = 0; j < fragSize; j++) {
    for (var kk = 0; kk < k; kk++) fb[kk] = availArrs[kk][j];
    for (var d = 0; d < k; d++) {
      var invRow = inv[d];
      var val = 0;
      for (var kk2 = 0; kk2 < k; kk2++) {
        if (invRow[kk2] !== 0 && fb[kk2] !== 0) val ^= gfMul(invRow[kk2], fb[kk2]);
      }
      result[d * fragSize + j] = val;
    }
  }
  return result.slice(0, originalSize);
}

function rsSelfTest() {
  // Vector generated by the real lib/core/erasure/reed_solomon.dart
  // (ReedSolomon, n=10 k=7) — see the dart-side cross-check that produced
  // it: encode 57 bytes, then decode from 7 of the 10 fragments.
  var originalHex = '436c656f6e6120626f6f7473747261702052532063726f73732d636865636b20766563746f7220303132333435363738394142434445462121';
  var fragHex = {
    0: '436c656f6e6120626f', 1: '6f7473747261702052', 2: '532063726f73732d63',
    3: '6865636b2076656374', 4: '6f7220303132333435', 5: '363738394142434445', 6: '462121000000000000',
    7: 'd9847f66bc1213ca18', 8: '4fdb836240d86cc297', 9: '80868760d86d575899'
  };

  // General path: 4 data + 3 parity fragments, missing data 0/3/5 — forces
  // the Gaussian-elimination branch, not the fast concatenation path.
  var mixMap = new Map();
  [1, 2, 4, 6, 7, 8, 9].forEach(function (idx) { mixMap.set(idx, hexToBytes(fragHex[idx])); });
  var mixDecoded = rsDecode(mixMap, 57, 10, 7);
  if (bytesToHex(mixDecoded) !== originalHex) throw new Error('mixed-fragment decode mismatch');

  // Fast path: all K data fragments present.
  var fastMap = new Map();
  for (var i = 0; i < 7; i++) fastMap.set(i, hexToBytes(fragHex[i]));
  var fastDecoded = rsDecode(fastMap, 57, 10, 7);
  if (bytesToHex(fastDecoded) !== originalHex) throw new Error('fast-path decode mismatch');
}

// ============================================================================
// Ed25519 (RFC 8032) — extended twisted-Edwards coordinates, curve parameter
// a = -1 (so the unified Hisil/Wong/Carter/Dawson addition/doubling formulas
// below are complete: no special-cased doubling, no exceptional points).
// Non-cofactored verification: [S]B == R + [k]A. Cross-checked at page load
// (ed25519SelfTest) against vectors signed by the real
// lib/core/crypto/sodium_ffi.dart (SodiumFFI, i.e. libsodium itself).
// ============================================================================

var ED_P = (1n << 255n) - 19n;
var ED_L = (1n << 252n) + 27742317777372353535851937790883648493n;

function emod(a, m) {
  var r = a % m;
  return r >= 0n ? r : r + m;
}
function modPow(base, exp, m) {
  base = emod(base, m);
  var result = 1n;
  while (exp > 0n) {
    if (exp & 1n) result = emod(result * base, m);
    base = emod(base * base, m);
    exp >>= 1n;
  }
  return result;
}
function modInv(a, m) { return modPow(a, m - 2n, m); }

var ED_D = emod(-121665n * modInv(121666n, ED_P), ED_P);
var ED_SQRT_M1 = modPow(2n, (ED_P - 1n) / 4n, ED_P);

var ED_IDENTITY = { x: 0n, y: 1n, z: 1n, t: 0n };
var ED_BASE = (function () {
  var bx = 15112221349535400772501151409588531511454012693041857206046113283949847762202n;
  var by = 46316835694926478169428394003475163141307993866256225615783033603165251855960n;
  return { x: emod(bx, ED_P), y: emod(by, ED_P), z: 1n, t: emod(bx * by, ED_P) };
})();

function pointAdd(p1, p2) {
  var a = emod((p1.y - p1.x) * (p2.y - p2.x), ED_P);
  var b = emod((p1.y + p1.x) * (p2.y + p2.x), ED_P);
  var c = emod(2n * ED_D * p1.t * p2.t, ED_P);
  var d = emod(2n * p1.z * p2.z, ED_P);
  var e = emod(b - a, ED_P);
  var f = emod(d - c, ED_P);
  var g = emod(d + c, ED_P);
  var h = emod(b + a, ED_P);
  return { x: emod(e * f, ED_P), y: emod(g * h, ED_P), z: emod(f * g, ED_P), t: emod(e * h, ED_P) };
}

function pointDouble(p) {
  var a = emod(p.x * p.x, ED_P);
  var b = emod(p.y * p.y, ED_P);
  var c = emod(2n * p.z * p.z, ED_P);
  var d = emod(ED_P - a, ED_P); // curve parameter a = -1
  var xy = emod(p.x + p.y, ED_P);
  var e = emod(xy * xy - a - b, ED_P);
  var g = emod(d + b, ED_P);
  var f = emod(g - c, ED_P);
  var h = emod(d - b, ED_P);
  return { x: emod(e * f, ED_P), y: emod(g * h, ED_P), z: emod(f * g, ED_P), t: emod(e * h, ED_P) };
}

function pointMul(p, scalar) {
  var result = ED_IDENTITY;
  var addend = p;
  var e = scalar;
  while (e > 0n) {
    if (e & 1n) result = pointAdd(result, addend);
    addend = pointDouble(addend);
    e >>= 1n;
  }
  return result;
}

function bytesToBigIntLE(bytes) {
  var v = 0n;
  for (var i = bytes.length - 1; i >= 0; i--) v = (v << 8n) | BigInt(bytes[i]);
  return v;
}

function pointDecompress(bytes) {
  if (bytes.length !== 32) throw new Error('bad point length');
  var signBit = (bytes[31] >> 7) & 1;
  var yBytes = bytes.slice();
  yBytes[31] &= 0x7F;
  var y = bytesToBigIntLE(yBytes);
  if (y >= ED_P) throw new Error('y out of range');

  var y2 = emod(y * y, ED_P);
  var u = emod(y2 - 1n, ED_P);
  var v = emod(ED_D * y2 + 1n, ED_P);
  var v3 = emod(v * v * v, ED_P);
  var v7 = emod(v3 * v3 * v, ED_P);
  var uv7 = emod(u * v7, ED_P);
  var exp = (ED_P - 5n) / 8n;
  var x = emod(u * v3 * modPow(uv7, exp, ED_P), ED_P);

  var vx2 = emod(v * x * x, ED_P);
  if (vx2 === emod(u, ED_P)) {
    // x is already correct
  } else if (vx2 === emod(ED_P - u, ED_P)) {
    x = emod(x * ED_SQRT_M1, ED_P);
  } else {
    throw new Error('not a valid curve point');
  }

  if (x === 0n && signBit === 1) throw new Error('invalid point encoding');
  if ((x & 1n) !== BigInt(signBit)) x = emod(ED_P - x, ED_P);

  return { x: x, y: y, z: 1n, t: emod(x * y, ED_P) };
}

function pointEquals(p1, p2) {
  var xz1 = emod(p1.x * p2.z, ED_P);
  var xz2 = emod(p2.x * p1.z, ED_P);
  var yz1 = emod(p1.y * p2.z, ED_P);
  var yz2 = emod(p2.y * p1.z, ED_P);
  return xz1 === xz2 && yz1 === yz2;
}

async function ed25519Verify(message, signature, publicKey) {
  if (signature.length !== 64 || publicKey.length !== 32) return false;
  var rBytes = signature.slice(0, 32);
  var sBytes = signature.slice(32, 64);
  var s = bytesToBigIntLE(sBytes);
  if (s >= ED_L) return false; // reject non-canonical S (signature malleability)

  var a, r;
  try {
    a = pointDecompress(publicKey);
    r = pointDecompress(rBytes);
  } catch (e) {
    return false;
  }

  var hDigest = await sha512Bytes(concatBytes(rBytes, publicKey, message));
  var k = emod(bytesToBigIntLE(hDigest), ED_L);

  var sB = pointMul(ED_BASE, s);
  var kA = pointMul(a, k);
  var rhs = pointAdd(r, kA);

  return pointEquals(sB, rhs);
}

async function ed25519SelfTest() {
  // Vectors generated and verified by the real
  // lib/core/crypto/sodium_ffi.dart (SodiumFFI.signEd25519 /
  // SodiumFFI.verifyEd25519, i.e. actual libsodium) — not memorized/assumed.
  var pubKeyHex = '0b50c08d567c009bb38a1b8ec4ba678f4370653d183f72804d86bd2d7609fc63';
  var emptyMsgSigHex = '7041c756bc3ee6bb9d511518495801c8a17a28a08df1a4099c83924b741a1457c864bf075b03fa1947cafbdc0d1a0e72516af968081e997cd23ee52ae0fc1705';
  var payloadMsgHex = '616e64726f69643a616161613131313162626262323232326363636333333333646464643434343465656565353535356666666636363636373737373838383839393939303030300a6c696e75783a313131316161616132323232626262623333333363636363343434346464646435353535656565653636363637373737383838383939393930303030313131310a332e312e313235';
  var payloadSigHex = '0af02365424ad84fa8909ab51a113c32e249a2e9708af42335e49dee1666103f001d01b04a5ef2115ccc5853f5ead4ab05955401066e42374e1ab6760a101207';

  var pubKey = hexToBytes(pubKeyHex);

  var okEmpty = await ed25519Verify(new Uint8Array(0), hexToBytes(emptyMsgSigHex), pubKey);
  if (okEmpty !== true) throw new Error('empty-message signature did not verify');

  var okPayload = await ed25519Verify(hexToBytes(payloadMsgHex), hexToBytes(payloadSigHex), pubKey);
  if (okPayload !== true) throw new Error('payload signature did not verify');

  var tampered = hexToBytes(payloadSigHex);
  tampered[0] ^= 0xFF;
  var okTampered = await ed25519Verify(hexToBytes(payloadMsgHex), tampered, pubKey);
  if (okTampered !== false) throw new Error('tampered signature was accepted');

  var okWrongMsg = await ed25519Verify(concatBytes(hexToBytes(payloadMsgHex), new Uint8Array([0])), hexToBytes(payloadSigHex), pubKey);
  if (okWrongMsg !== false) throw new Error('signature over the wrong message was accepted');
}

// ============================================================================
// Invite link (§19.6.4) — hash-fragment parsing.
// The `m` parameter carries per-platform Ed25519 signatures (JSON map of
// platform -> base64 signature). Each signature covers the raw 32-byte
// SHA-256 hash of that platform's binary — same format as UpdateManifest
// binarySignatures. No combined hash-map payload.
// ============================================================================

var PARAMS = {};
var PLATFORM = 'unknown';

function parseHashParams() {
  var hash = window.location.hash || '';
  if (hash.charAt(0) === '#') hash = hash.slice(1);
  var out = {};
  hash.split('&').forEach(function (part) {
    if (!part) return;
    var idx = part.indexOf('=');
    if (idx < 0) return;
    var key = part.slice(0, idx);
    var raw = part.slice(idx + 1);
    try { out[key] = decodeURIComponent(raw); } catch (e) { out[key] = raw; }
  });
  return out;
}

// ============================================================================
// Platform detection
// ============================================================================

// Per-platform Reed-Solomon N/K (Architecture §19.6.2 erasure table).
var RS_PARAMS = {
  android: { n: 30, k: 21 },
  linux: { n: 50, k: 35 },
  windows: { n: 50, k: 35 },
  macos: { n: 50, k: 35 },
  ios: { n: 40, k: 28 }
};

function detectPlatform() {
  var ua = navigator.userAgent.toLowerCase();
  if (ua.indexOf('android') !== -1) return 'android';
  if (ua.indexOf('iphone') !== -1 || ua.indexOf('ipod') !== -1) return 'ios';
  if (ua.indexOf('ipad') !== -1) return 'ios';
  if (ua.indexOf('mac os x') !== -1 || ua.indexOf('macintosh') !== -1) {
    // iPadOS 13+ reports a desktop Mac UA; distinguish via touch support.
    if (navigator.maxTouchPoints && navigator.maxTouchPoints > 1) return 'ios';
    return 'macos';
  }
  if (ua.indexOf('windows') !== -1) return 'windows';
  if (ua.indexOf('linux') !== -1) return 'linux';
  return 'unknown';
}

function renderPlatformPicker(detected) {
  var el = $('platform-picker');
  el.innerHTML = '';
  ['linux', 'windows', 'android', 'macos', 'ios'].forEach(function (p) {
    var btn = document.createElement('button');
    btn.type = 'button';
    btn.textContent = p;
    if (p === detected) btn.classList.add('active');
    btn.onclick = function () {
      Array.prototype.forEach.call(el.children, function (c) { c.classList.remove('active'); });
      btn.classList.add('active');
      if (p === 'ios') { showIosNotice(); return; }
      startForPlatform(p);
    };
    el.appendChild(btn);
  });
}

// ============================================================================
// Nostr binary discovery (§19.6.5) — best-effort additional-node lookup.
//
// The invite link (§19.6.4 format: s/h/m/v/f only) does not carry the
// `invite_binary_key` needed to compute the record's `d` tag or decrypt its
// content — that key is derived from network_secret, which Bob does not
// have yet. queryNostrRelay() below is a complete, working NIP-33 query
// implementation, ready for a future link revision that adds an invite
// nonce; until then discoverAdditionalNodes() intentionally returns no
// candidates instead of querying relays with a tag no publisher would ever
// use, and the assembler falls back to the node that served this page —
// which is the expected path during the network's bootstrap phase anyway
// (§19.6.1 principle 5: bootstrap nodes hold complete binaries for every
// platform).
// ============================================================================

var NOSTR_RELAYS = [
  'wss://relay.damus.io',
  'wss://nos.lol',
  'wss://relay.snort.social',
  'wss://relay.primal.net'
];

function queryNostrRelay(relayUrl, dTag, timeoutMs) {
  return new Promise(function (resolve) {
    var events = [];
    var settled = false;
    var ws = null;
    var timer = setTimeout(finish, timeoutMs);

    function finish() {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      try { if (ws) ws.close(); } catch (e) { /* ignore */ }
      resolve(events);
    }

    try {
      ws = new WebSocket(relayUrl);
    } catch (e) {
      finish();
      return;
    }

    var subId = 'cleona-' + Math.random().toString(36).slice(2, 10);
    ws.onopen = function () {
      var filter = { kinds: [30078], '#d': [dTag], limit: 20 };
      try { ws.send(JSON.stringify(['REQ', subId, filter])); } catch (e) { finish(); }
    };
    ws.onmessage = function (ev) {
      try {
        var msg = JSON.parse(ev.data);
        if (msg[0] === 'EVENT' && msg[1] === subId) {
          events.push(msg[2]);
        } else if (msg[0] === 'EOSE' && msg[1] === subId) {
          finish();
        }
      } catch (e) { /* ignore malformed relay message */ }
    };
    ws.onerror = finish;
    ws.onclose = finish;
  });
}

async function discoverAdditionalNodes(platform, timeoutMs) {
  if (!PARAMS.n) {
    log('Nostr: this invite link has no invite-scoped key (n=) — using the serving node directly.');
    return [];
  }
  setStatus('Looking for additional download sources on Nostr…');
  var dTag = PARAMS.n + ':' + platform;
  var lists = await Promise.all(NOSTR_RELAYS.map(function (r) {
    return queryNostrRelay(r, dTag, timeoutMs || 4000);
  }));
  var flat = [];
  lists.forEach(function (list) { list.forEach(function (ev) { flat.push(ev); }); });
  log('Nostr: found ' + flat.length + ' candidate record(s) across ' + NOSTR_RELAYS.length + ' relays.');
  return flat;
}

// ============================================================================
// HTTP download (§19.6.6: GET /cleona/binary/<platform>, GET
// /cleona/fragment/<platform>/<index>) with progress reporting.
// ============================================================================

function nodeOrigin() { return window.location.protocol + '//' + window.location.host; }

async function fetchWithProgress(url, onProgress) {
  var resp = await fetch(url, { cache: 'no-store' });
  if (!resp.ok) {
    var err = new Error('HTTP ' + resp.status);
    err.status = resp.status;
    throw err;
  }
  var lengthHeader = resp.headers.get('Content-Length');
  var total = lengthHeader ? parseInt(lengthHeader, 10) : 0;
  if (!resp.body || !resp.body.getReader) {
    var buf = await resp.arrayBuffer();
    if (onProgress) onProgress(buf.byteLength, buf.byteLength || total);
    return new Uint8Array(buf);
  }
  var reader = resp.body.getReader();
  var chunks = [];
  var received = 0;
  for (;;) {
    var res = await reader.read();
    if (res.done) break;
    chunks.push(res.value);
    received += res.value.length;
    if (onProgress) onProgress(received, total);
  }
  var out = new Uint8Array(received);
  var offset = 0;
  chunks.forEach(function (c) { out.set(c, offset); offset += c.length; });
  return out;
}

async function headContentLength(url) {
  try {
    var resp = await fetch(url, { method: 'HEAD', cache: 'no-store' });
    if (!resp.ok) return null;
    var len = resp.headers.get('Content-Length');
    return len ? parseInt(len, 10) : null;
  } catch (e) {
    return null;
  }
}

async function downloadCompleteBinary(origin, platform) {
  var url = origin + '/cleona/binary/' + encodeURIComponent(platform);
  log('Trying complete binary: ' + url);
  setStep('fetch', 'active');
  return await fetchWithProgress(url, function (received, total) {
    var frac = total > 0 ? received / total : 0;
    setProgress(frac, formatBytes(received) + (total ? ' / ' + formatBytes(total) : ''));
  });
}

async function downloadViaFragments(origin, platform) {
  var rs = RS_PARAMS[platform];
  if (!rs) throw new Error('No Reed-Solomon parameters known for platform "' + platform + '"');
  var n = rs.n, k = rs.k;

  // Fragment endpoints carry no total-size metadata (§19.6.6), and the
  // Nostr binary-availability record (§19.6.5) does not include one either.
  // The original size is required to trim Reed-Solomon block padding, so a
  // HEAD to the complete-binary endpoint is the only way to learn it — this
  // succeeds whenever *any* directly reachable node advertises a complete
  // binary for this platform, which is the common bootstrap-phase case.
  var originalSize = await headContentLength(origin + '/cleona/binary/' + encodeURIComponent(platform));
  if (originalSize === null) {
    throw new Error('This node cannot report the exact binary size, so fragments cannot be safely trimmed after assembly');
  }

  var fragments = new Map();
  var order = [];
  for (var i = 0; i < k; i++) order.push(i);
  for (var p = k; p < n; p++) order.push(p);

  for (var idx = 0; idx < order.length && fragments.size < k; idx++) {
    var fragIndex = order[idx];
    var url = origin + '/cleona/fragment/' + encodeURIComponent(platform) + '/' + fragIndex;
    try {
      var data = await fetchWithProgress(url, function () {
        setProgress(fragments.size / k, fragments.size + '/' + k + ' fragments');
      });
      fragments.set(fragIndex, data);
      setProgress(fragments.size / k, fragments.size + '/' + k + ' fragments');
      log('Got fragment ' + fragIndex + ' (' + formatBytes(data.length) + ')');
    } catch (e) {
      log('Fragment ' + fragIndex + ' unavailable: ' + e.message);
    }
  }

  if (fragments.size < k) {
    throw new Error('Only got ' + fragments.size + ' of ' + k + ' required fragments');
  }

  setStatus('Assembling binary from ' + k + ' fragments…');
  return rsDecode(fragments, originalSize, n, k);
}

// ============================================================================
// Verification + final offer
// ============================================================================

function suggestedExtension(platform) {
  switch (platform) {
    case 'android': return '.apk';
    case 'windows': return '.exe';
    case 'macos': return '.dmg';
    case 'linux': return '.AppImage';
    default: return '.bin';
  }
}

async function verifyAndOffer(binary, expectedHashHex, platform, version) {
  setStep('fetch', 'done');
  setStep('verify', 'active');
  setStatus('Verifying download…');
  setProgress(1, 'checking SHA-256…');

  var gotHashHex = await sha256Hex(binary);
  if (gotHashHex.toLowerCase() !== String(expectedHashHex).toLowerCase()) {
    throw new Error('Hash mismatch — expected ' + expectedHashHex + ', got ' + gotHashHex);
  }
  log('SHA-256 OK: ' + gotHashHex);

  setStep('verify', 'done');
  setStep('ready', 'active');
  setProgress(1, 'verified');

  var blob = new Blob([binary], { type: 'application/octet-stream' });
  var blobUrl = URL.createObjectURL(blob);
  var filename = 'cleona-' + platform + '-' + version + suggestedExtension(platform);

  setStatus('Binary verified. Ready to install.');
  showBanner('ok', 'Verified — SHA-256 hash and Ed25519 maintainer signature both match. Safe to install.');
  setStep('ready', 'done');
  setAction('Download Cleona (' + formatBytes(binary.length) + ')', function () {
    var a = document.createElement('a');
    a.href = blobUrl;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    log('Download offered as ' + filename + '. If your browser warns about an ' +
      'insecure/unverified file, that is expected for a plain-HTTP download — ' +
      'the SHA-256 hash above already confirms its integrity.');
  }, true);
}

// ============================================================================
// Orchestration
// ============================================================================

function resetProgressUi() {
  setStep('fetch', null); setStep('verify', null); setStep('ready', null);
  setProgress(0, '');
  showBanner('warn', null);
  showBanner('err', null);
  showBanner('ok', null);
  setAction('Working…', null, false);
}

function handleDownloadFailure(e) {
  log('Download failed: ' + e.message);
  if (PARAMS.f) {
    setStatus('Could not download from this node.');
    showBanner('warn', 'This node could not provide the ' + PLATFORM + ' binary (' + e.message + '). ' +
      'You can try the external fallback link instead — its integrity can still be checked ' +
      'afterwards against the SHA-256 hash shown in Details below.');
    setAction('Open fallback link', function () { window.location.href = PARAMS.f; }, true);
  } else {
    setStatus('Download failed');
    showBanner('err', 'Could not download or assemble the Cleona binary for ' + PLATFORM + ' (' + e.message + '). ' +
      'Please try again later, or ask your contact for a new invite link.');
    setAction('Retry', function () { startForPlatform(PLATFORM); }, true);
  }
}

async function startForPlatform(platform) {
  PLATFORM = platform;
  resetProgressUi();

  var hashesJson, binaryHashes;
  try {
    hashesJson = bytesToUtf8(base64ToBytes(PARAMS.h));
    binaryHashes = JSON.parse(hashesJson);
  } catch (e) {
    showBanner('err', 'Could not read the binary hash list from this invite link (' + e.message + ').');
    setAction('Cannot continue', null, false);
    return;
  }

  var expectedHash = binaryHashes[platform];
  if (!expectedHash) {
    showBanner('err', 'This invite link does not include a binary for "' + platform + '".');
    setAction('Cannot continue', null, false);
    return;
  }
  $('detail-hash').textContent = expectedHash;

  setStatus('Verifying invite link signature…');
  var binarySignatures;
  try {
    binarySignatures = JSON.parse(bytesToUtf8(base64ToBytes(PARAMS.m)));
  } catch (e) {
    showBanner('err', 'The invite link signatures are malformed.');
    setAction('Cannot continue', null, false);
    return;
  }

  var platformSigBase64 = binarySignatures[platform];
  if (!platformSigBase64) {
    showBanner('err', 'This invite link does not include a signature for "' + platform + '".');
    setAction('Cannot continue', null, false);
    return;
  }

  var signatureBytes = base64ToBytes(platformSigBase64);
  var hashBytes = hexToBytes(expectedHash);
  var pubKeyBytes = hexToBytes(MAINTAINER_PUBLIC_KEY_HEX);
  var sigOk = await ed25519Verify(hashBytes, signatureBytes, pubKeyBytes);
  if (!sigOk) {
    showBanner('err', 'Maintainer signature verification FAILED. This invite link may be forged — do not install anything from it.');
    setStatus('Signature verification failed');
    setAction('Do not install', null, false);
    log('Maintainer signature check FAILED — aborting before any download.');
    return;
  }
  log('Maintainer signature OK for v' + PARAMS.v + ' (' + platform + ': ' + expectedHash + ')');
  setStatus('Downloading Cleona for ' + platform + '…');

  var origin = nodeOrigin();
  var binary = null;

  try {
    binary = await downloadCompleteBinary(origin, platform);
    log('Downloaded complete binary (' + formatBytes(binary.length) + ')');
  } catch (e) {
    log('Complete binary unavailable (' + e.message + ') — trying erasure fragments…');
    setStatus('Full binary unavailable — assembling from fragments…');
    try {
      var candidates = await discoverAdditionalNodes(platform, 4000);
      candidates.forEach(function (c) { log('Nostr candidate record received.'); });
      binary = await downloadViaFragments(origin, platform);
      log('Assembled binary from fragments (' + formatBytes(binary.length) + ')');
    } catch (e2) {
      handleDownloadFailure(e2);
      return;
    }
  }

  try {
    await verifyAndOffer(binary, expectedHash, platform, PARAMS.v);
  } catch (e) {
    showBanner('err', e.message);
    setStatus('Verification failed');
    setAction('Verification failed — do not install', null, false);
    log('FATAL: ' + e.message);
  }
}

function showIosNotice() {
  PLATFORM = 'ios';
  resetProgressUi();
  setStatus('On iOS, Cleona is available through the App Store.');
  showBanner('warn', 'Apple does not allow installing apps from outside the App Store on most ' +
    'devices (the EU DMA sideloading exception applies only to iOS 17.4+ in EU markets). ' +
    'Please install Cleona from the App Store instead.');
  setAction('Open App Store', function () { window.location.href = 'https://apps.apple.com/app/cleona'; }, true);
}

function fatalCryptoError(message) {
  setStatus('This page failed a security self-test and cannot continue.');
  showBanner('err', message + ' — the download cannot be safely verified in this browser. ' +
    'Please try a different, up-to-date browser, or download Cleona from the official website instead.');
  setAction('Cannot continue', null, false);
  log('FATAL (self-test): ' + message);
}

async function main() {
  try {
    rsSelfTest();
  } catch (e) {
    fatalCryptoError('Reed-Solomon self-test failed (' + e.message + ')');
    return;
  }
  try {
    await ed25519SelfTest();
  } catch (e) {
    fatalCryptoError('Ed25519 self-test failed (' + e.message + ')');
    return;
  }
  log('Crypto self-tests passed (Reed-Solomon + Ed25519).');

  PARAMS = parseHashParams();
  if (!PARAMS.s || !PARAMS.h || !PARAMS.m || !PARAMS.v) {
    setStatus('Invalid invite link');
    showBanner('err', 'This link is missing required parameters. Ask the person who sent it for a new invite.');
    setAction('Cannot continue', null, false);
    return;
  }
  $('detail-version').textContent = PARAMS.v;

  var detected = detectPlatform();
  renderPlatformPicker(detected);

  if (detected === 'unknown') {
    $('platform-badge').textContent = 'Platform not detected — pick one below';
    setStatus('Select your platform above to continue.');
    setAction('Select a platform', null, false);
    return;
  }
  $('platform-badge').textContent = 'Detected: ' + detected;

  if (detected === 'ios') {
    showIosNotice();
    return;
  }

  await startForPlatform(detected);
}

window.addEventListener('error', function (e) {
  log('Unhandled error: ' + (e && e.message ? e.message : e));
});

main();
})();
</script>
</body>
</html>
'''
        .replaceFirst(
          'var MAINTAINER_PUBLIC_KEY_HEX = "__MAINTAINER_PUBLIC_KEY_HEX__";',
          'var MAINTAINER_PUBLIC_KEY_HEX = "$maintainerPublicKeyHex";',
        );
  }
}
